# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-01 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dprfile',
            name='user',
        ),
    ]
