# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 20:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ninja', '0002_remove_dprfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dprfile',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
